name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Get CMake
      uses: symbitic/install-cmake@master
    - name: CMake the project
      run: cmake .
    - name: make
      run: make
    - name: test
      run: ModbusSlave test
